name: CI - Testes e Build Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  testar_e_buildar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest

      - name: Build da imagem Docker
        run: |
          docker build -t ci-cd-fastapi-demo:ci .
